#!/usr/bin/env ansible-playbook
---
- hosts: all
  roles:
    - common
- hosts: plex
  roles:
    - plex
    - ansible
- hosts: durandal
  tasks:
    - import_tasks: durandal.yml
- hosts: wafflemaker
  tasks:
    - import_tasks: wafflemaker.yml
