#!/usr/bin/env ansible-playbook
---
- hosts: all
  roles:
    - common
- hosts: local
  roles:
    - local
- hosts: plex
  roles:
    - plex
    - ansible
- name: Set up Wafflemaker
  import_playbook: wafflemaker.yml
- name: Set up Durandal
  import_playbook: durandal.yml
