#!/usr/bin/env ansible-playbook
---
- name: Run common setup
  import_playbook: common.yml
- name: Setup plex
  import_playbook: plex.yml
- name: Setup Durandal
  import_playbook: durandal.yml
- name: Setup Wafflemaker
  import_playbook: wafflemaker.yml
