#!/usr/bin/env ansible-playbook
---
- hosts: all
  roles:
    - common
- hosts: local
  roles:
    - local
- hosts: plex
  roles:
    - plex
    - ansible
- name: Set up Macbook
  import_playbook: macbook.yml
- name: Set up Durandal
  import_playbook: durandal.yml
