#!/usr/bin/env ansible-playbook
---
- hosts: wafflemaker
  tasks:
    - import_playbook: wafflemaker.yml
- hosts: all
  roles:
    - common
- hosts: plex
  roles:
    - plex
    - ansible
- hosts: durandal
  tasks:
    - import_playbook: durandal.yml
