---
- name: Configure SSH on Unix systems
  import_tasks: unix.yml
  when: ansible_os_family != 'Windows'
- name: Configure SSH on Windows systems
  import_tasks: windows.yml
  when: ansible_os_family == 'Windows'
