---
- name: Use smart gathering in ansible
  lineinfile:
    path: /etc/ansible/ansible.cfg
    line: gathering = smart
    state: present
    create: yes
    regexp: '#?gathering = (smart|implicit|explicit)'
  become: yes
- name: Ensure Ansible can be run on on demand on Windows
  lineinfile:
    path: ~/.zshenv
    line: export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
    state: present
    create: yes
    regexp: '^(export )?OBJC_DISABLE_INITIALIZE_FORK_SAFETY='
- name: Ensure Ansible can run periodically on Windows
  cron:
    user: root
    env: yes
    name: OBJC_DISABLE_INITIALIZE_FORK_SAFETY
    job: 'YES'
    state: absent
  become: yes
- name: Ensure Ansible runs every hour from 7am to 7pm
  cron:
    name: /etc/ansible/site.yml
    user: root
    job: ansible-playbook /etc/ansible/site.yml >> /dev/null 2>&1
    minute: '0'
    hour: 7-19
    state: present
  become: yes
