---
# TODO: figure out how to install homebrew
- name: Install commands on Macs
  homebrew:
    name: '{{ item }}'
    state: latest
    update_homebrew: yes
  loop: '{{ commands }}'
- name: Install applications on Macs
  homebrew_cask:
    name: '{{ item }}'
    state: upgraded
  loop: '{{ applications }}'
- name: Enable key repeat on Macs
  osx_defaults:
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
    state: present
- name: Create quick action for VS Code
  copy:
    src: Open In VS Code.workflow
    dest: ~/Library/Services/
  when: '"visual-studio-code" in applications'