---
- name: Install commands on Macs
  homebrew:
    name: '{{ commands }}'
    state: latest
    update_homebrew: yes
- name: Install applications on Macs
  homebrew_cask:
    name: '{{ applications }}'
    state: latest
