---
# TODO: figure out how to install homebrew
- name: Install commands on Macs
  homebrew:
    name: '{{ item }}'
    state: latest
    update_homebrew: yes
  loop: '{{ commands }}'
- name: Install applications on Macs
  homebrew_cask:
    name: '{{ item }}'
    state: upgraded
  loop: '{{ applications }}'
