---
# TODO: figure out how to install homebrew
- name: Install commands on Macs
  homebrew:
    name: '{{ commands }}'
    state: latest
    update_homebrew: yes
    upgrade_all: yes
- name: Install applications on Macs
  homebrew_cask:
    name: '{{ applications }}'
    state: latest
    upgrade_all: yes
