---
- name: Setup Mac machines
  import_tasks: mac.yml
  when: ansible_facts.os_family == 'Darwin'
- name: Setup Windows machines
  import_tasks: windows.yml
  when: ansible_facts.os_family == 'Windows'
- name: Setup Z Shell on Unix machines
  import_tasks: zsh.yml
  when: ansible_facts.os_family != 'Windows'
