---
- name: Install software on Windows systems
  when: ansible_facts.os_family == 'Windows'
  win_chocolatey:
    name: '{{ applications }}'
    state: latest
- name: Install AHK scripts
  tags:
    - y
  win_copy:
    src: files/ahk/
    dest: '{{ home }}\AHKScripts'
- name: Run main.ahk on startup
  win_shortcut:
    src: '{{ home }}\AHKScripts\main.ahk'
    directory: '{{ home }}\AHKScripts'
    dest: '{{ home }}\\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\main.lnk'
    icon: '{{ home }}\AHKScripts\main.ahk,0'
