---
- name: Install zsh on Debian systems
  package:
    name: zsh
    state: latest
  become: yes
  when: ansible_facts.os_family = 'Debian'
- name: Remove zplug on Debian systems
  package:
    name: zplug
    state: absent
  become: yes
  when: ansible_facts.os_family = 'Debian'
- name: Don't use package managed version of zplug
  package:
    name: zplug
    state: absent
  when: ansible_facts.os_family != 'Debian'
- name: Install zplug from github.
  shell:
    cmd: curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
    creates: ~/.zplug/
- name: source zplug in ~/.zshrc
  lineinfile:
    path: ~/.zshrc
    create: yes
    regexp: 'source ~/\.zplug/init\.zsh'
    state: present
    insertbefore: BOF
    line: "source ~/.zplug/init.zsh\n"
- name: Allow zplug to manage itself
  lineinfile:
    path: ~/.zshrc
    create: yes
    regexp: 'zplug (''zplug/zplug''|"zplug/zplug")'
    state: present
    insertafter: '(?<=source ~/.zplug/init.zsh)^$'
    line: "zplug 'zplug/zplug', hook-build:'zplug --self-manage'\n"
- name: Install and load zsh plugins in ~/.zshrc
  blockinfile:
    path: ~/.zshrc
    create: yes
    state: present
    insertafter: EOF
    block: |
      # Install plugins if there are plugins that have not been installed
      if ! zplug check --verbose; then
          printf "Install? [y/N]: "
          if read -q; then
              echo; zplug install
          fi
      fi

      # Then, source plugins and add commands to $PATH
      zplug load \
      # --verbose
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
- name: Load 'oh-my-zsh' plugins
  lineinfile:
    path: ~/.zshrc
    create: yes
    regexp: 'zplug ([''"]{{ item }}[''"])'
    state: present
    insertbefore: '# BEGIN ANSIBLE MANAGED BLOCK'
    line: "zplug '{{ item }}', from:oh-my-zsh\n"
  loop: '{{ oh_my_zsh_plugins }}'
- name: Load wp-cli plugin when wp-cli is installed
  lineinfile:
    path: ~/.zshrc
    create: yes
    regexp: zplug ['"]plugins/wp['"]
    line: "zplug 'plugins/wp', defer: 2, if:'[[ command -z wp ]]'"
- name: Load a zsh theme
  lineinfile:
    path: ~/.zshrc
    create: yes
    regexp: 'zplug .*, as:theme'
    state: present
    insertbefore: '# BEGIN ANSIBLE MANAGED BLOCK'
    line: "zplug 'themes/{{ zsh_theme }}', as:theme, from:oh-my-zsh, on:'plugins/vi_mode'\n"
- name: Track zsh history
  lineinfile:
    path: ~/.zshenv
    create: yes
    regexp: HISTSIZE=
    line: HISTSIZE=1000
    state: present
- name: Save zsh history
  lineinfile:
    path: ~/.zshenv
    create: yes
    regexp: SAVEHIST=
    line: SAVEHIST=1000
    insertafter: HISTSIZE=
    state: present
- name: Set zsh history file location
  lineinfile:
    path: ~/.zshenv
    create: yes
    regexp: HISTFILE=
    line: HISTFILE=~/.history
    insertafter: SAVEHIST=
    state: present
# TODO:  setopt HIST_IGNORE_DUPS
